### ISSUE TITLE
Will Not Open/Decompile Ch26 of Awakening

### ISSUE THREAD

**Issue by Reddazrael** [thane98/Exalt#1]
@thane98 

I get the following error message when I drag and drop FE13's "026.cmb" (the final chapter, Endgame: Grima) onto Decompile.bat:

Warning: unrecognized event type: 12. Event arguments may be incorrect!
Warning: unrecognized event type: 15. Event arguments may be incorrect!
Warning: unrecognized event type: 16. Event arguments may be incorrect!
Warning: unrecognized event type: 19. Event arguments may be incorrect!
Warning: unrecognized event type: 19. Event arguments may be incorrect!
Warning: unrecognized event type: 19. Event arguments may be incorrect!
Warning: unrecognized event type: 19. Event arguments may be incorrect!
Warning: unrecognized event type: 19. Event arguments may be incorrect!
Warning: unrecognized event type: 19. Event arguments may be incorrect!
Warning: unrecognized event type: 21. Event arguments may be incorrect!
Decompiling Failed!
Unexpected operator in shorthand assignment at 7923.

---

Additionally, Exalt.jar will not open the file. There is a lot going on in that chapter, so I'm assuming it uses unrecognized scripts? Either way, just wanted to let you know.

**Comment by thane98** [comment]
It looks like that chapter uses some event types that Exalt doesn't know how to handle yet. That should be a quick fix.

The unexpected operator error could be a tougher issue to fix - an error like that usually means the script's doing something strange.

I'll try to fix it when I get the chance. Thanks!

**Comment by Reddazrael** [comment]
Good god, you're fast with replies. Thanks so much!

**Comment by thane98** [comment]
I've put out an [update](https://github.com/thane98/Exalt/releases/tag/0.4.1) which should improve compatibility with scripts from Awakening. 026 should decompile and compile without any issues. Let me know if you run into any other problems with the chapter.

**Comment by Reddazrael** [comment]
That was fast! And it all looks great. Thanks so much! I'm really enjoying the tool, so I appreciate that you've made it.
